apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: super-duper-meme
spec:
  selector:
    matchLabels:
      app: super-duper-meme
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: super-duper-meme
    spec:
      containers:
      - name: frontend
        image: super-duper-meme_frontend:latest
        ports:
        - containerPort: 9000
      - name: api
        image: super-duper-meme_api:latest
        ports:
        - containerPort: 9001
